# -*- coding: utf-8 -*-
"""papua_new_guinea.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vrkdRgMly_9eSJ7DKYxANFEwp8GeAoDv
"""

!pip install datasets
!pip install pystac
!pip install planetary_computer
!pip install rioxarray
!pip install pandas
!pip install numpy

# Commented out IPython magic to ensure Python compatibility.
import os
import sys
import csv
import glob
import joblib
import datasets
import numpy as np
import pandas as pd
from pathlib import Path

# Machine Learning imports
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier as cumlRF
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
from sklearn.metrics import classification_report
from sklearn.model_selection import RandomizedSearchCV, KFold
from itertools import combinations
from sklearn.preprocessing import PolynomialFeatures
from sklearn.decomposition import PCA

# Visualization imports
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

# Geospatial related imports
from osgeo import gdalconst
from osgeo import gdal

from pprint import pprint

# Ignore a few warnings for cleaner output
warnings.filterwarnings('ignore')
# %matplotlib inline

"""# HREA: High Resolution Electricity Access
Settlement-level measures of electricity access, reliability, and usage derived from VIIRS satellite imagery
"""

import pystac
import planetary_computer
import rioxarray
import matplotlib.pyplot as plt

# Item URL for HREA data in Papua New Guinea
item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/HREA_Papua_New_Guinea_2019_v1.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'light-composite', 'night-proportion', 'estimated-brightness')
asset_key = "light-composite"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
plt.imshow(ds.data[0], cmap="viridis")
plt.colorbar(label=f"{asset_key} values")
plt.title(f"HREA Data Visualization - {asset_key}")
plt.show()

"""# **MODIS Land Surface Temperature/Emissivity Daily**
Daytime land surface temperature daily 1km (Kelvin)
"""

import pystac
import planetary_computer
import rioxarray
import matplotlib.pyplot as plt

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A1.A2024007.h32v09.061.2024009121422.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "QC_Day"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A1.A2024007.h32v09.061.2024009121422.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "Emis_31"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A1.A2024007.h32v09.061.2024009121422.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "QC_Night"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A1.A2024007.h32v09.061.2024009121422.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "LST_Day_1km"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A1.A2024007.h32v09.061.2024009121422.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "Clear_day_cov"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A1.A2024007.h32v09.061.2024009121422.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "Day_view_angl"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A1.A2024007.h32v09.061.2024009121422.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "LST_Night_1km"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A1.A2024007.h32v09.061.2024009121422.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "Clear_night_cov"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

"""# MODIS Land Surface Temperature/Emissivity 8-Day
Daytime land surface temperature 8-day 1km (Kelvin)
"""

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A2.A2023361.h32v09.061.2024006200620.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "Emis_31"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A2.A2023361.h32v09.061.2024006200620.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "Night_view_angl"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A2.A2023361.h32v09.061.2024006200620.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "Night_view_time"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A2.A2023361.h32v09.061.2024006200620.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "QC_Night"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

import pystac
import planetary_computer
import rioxarray
import matplotlib.pyplot as plt

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A2.A2023361.h32v09.061.2024006200620.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "Day_view_angl"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/MYD11A2.A2023361.h32v09.061.2024006200620.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'Emis_31', 'Emis_32', 'QC_Night', 'LST_Day_1km', 'Clear_day_cov', 'Day_view_angl', 'Day_view_time', 'LST_Night_1km', 'Clear_night_cov', 'Night_view_angl', 'Night_view_time')
asset_key = "LST_Day_1km"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"MODIS Land Surface Temperature/Emissivity Daily - {asset_key}")
plt.show()

"""# **Global Surface Water**
Global surface water distribution and dynamics from 1984 to 2020
"""

import pystac
import planetary_computer
import rioxarray
import matplotlib.pyplot as plt

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/140E_0Nv1_3_2020.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'extent', 'occurrence', 'recurrence', 'seasonality', 'transitions')
asset_key = "change"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"JRC Global Surface Water - {asset_key}")
plt.show()

import pystac
import planetary_computer
import rioxarray
import matplotlib.pyplot as plt

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/140E_0Nv1_3_2020.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'extent', 'occurrence', 'recurrence', 'seasonality', 'transitions')
asset_key = "occurrence"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"JRC Global Surface Water - {asset_key}")
plt.show()

import pystac
import planetary_computer
import rioxarray
import matplotlib.pyplot as plt

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/140E_0Nv1_3_2020.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open one of the data assets (other asset keys to use: 'extent', 'occurrence', 'recurrence', 'seasonality', 'transitions')
asset_key = "recurrence"
asset_href = signed_item.assets[asset_key].href
ds = rioxarray.open_rasterio(asset_href)

# Select a specific band for visualization (adjust '1' to the desired band index)
selected_band = ds.sel(band=1)

# Plot the raster data using Matplotlib
plt.figure(figsize=(10, 10))
selected_band.plot.imshow(cmap="viridis", add_colorbar=True)
plt.title(f"JRC Global Surface Water - {asset_key}")
plt.show()

"""# **Landsat Collection 2 Level-1**"""

import pystac
import planetary_computer
import rioxarray
import xarray as xr
import matplotlib.pyplot as plt

item_url = "https://raw.githubusercontent.com/Madhesh-V/Nasa-Pale-Blue-Dot-Project/main/Clean%20Water%20and%20Sanitation/raw%20data/papua_new_guinea/LC08_L2SP_098066_20220319_02_T1.json"

# Load the individual item metadata and sign the assets
item = pystac.Item.from_file(item_url)
signed_item = planetary_computer.sign(item)

# Open red, green, and blue bands for a true-color image
red_band = rioxarray.open_rasterio(signed_item.assets["red"].href)
green_band = rioxarray.open_rasterio(signed_item.assets["green"].href)
blue_band = rioxarray.open_rasterio(signed_item.assets["blue"].href)

# Concatenate the bands along a new dimension
true_color_image = xr.concat([red_band, green_band, blue_band], dim="band")

# Plot the true-color image
plt.figure(figsize=(10, 10))
true_color_image.plot.imshow(vmin=0, vmax=3000)  # Adjust vmin and vmax based on the data range
plt.title("Landsat Collection 2 Level-2 True-Color Image")
plt.show()